//
// Created by eric on 18-10-30.
//

#ifndef HYPER_DISTRIBUTOR_HYPERDISTRIBUTOR_H
#define HYPER_DISTRIBUTOR_HYPERDISTRIBUTOR_H

class HyperDistributor
{

};

#endif //HYPER_DISTRIBUTOR_HYPERDISTRIBUTOR_H
